BEGIN;


-- On s'assure que la table soit supprimée avant d'être créée pour éviter tout problème
DROP TABLE IF EXISTS "plat", "contact", "admin", "avis";

-- ---------------------------------------
-- Table "admin"
-- ---------------------------------------
CREATE TABLE IF NOT EXISTS "admin" (
    "id" integer GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    "username" text NOT NULL,
    "email" VARCHAR(255) NOT NULL,
    "password" text NOT NULL,
    "created_at" timestamptz NOT NULL DEFAULT CURRENT_TIMESTAMP,
    "updated_at" timestamptz
);

-- ---------------------------------------
-- Table "plat"
-- ---------------------------------------
CREATE TABLE IF NOT EXISTS "plat" (
    "id" integer GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    "name" text NOT NULL,
    "price" integer NOT NULL,
    "description" text NOT NULL,
    "image" text,
    "admin_id" integer NOT NULL REFERENCES "admin" ("id"),
    "created_at" timestamptz NOT NULL DEFAULT CURRENT_TIMESTAMP,
    "updated_at" timestamptz
);

-- ---------------------------------------
-- Table "contact"
-- ---------------------------------------
CREATE TABLE IF NOT EXISTS "contact" (
    "id" integer GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    "contact" text NOT NULL,
    "created_at" timestamptz NOT NULL DEFAULT CURRENT_TIMESTAMP,
    "updated_at" timestamptz
);

-- --------------------------------------
-- Table "avis"
-- --------------------------------------
CREATE TABLE IF NOT EXISTS "avis" (
    "id" integer GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    "first_name" VARCHAR (255) NOT NULL,
    "last_name" VARCHAR (255) NOT NULL,
    "email" VARCHAR (255) NOT NULL,
    "commentaire" text NOT NULL,
    "created_at" timestamptz NOT NULL DEFAULT CURRENT_TIMESTAMP,
    "updated_at" timestamptz
);


-- -----------------------------------------------
-- Insertion des données dans la table "admin"
-- -----------------------------------------------
INSERT INTO "admin" ("username", "email", "password") VALUES
('admin', 'admin@example.com', 'superadmin');

-- -----------------------------------------------
-- Insertion des données dans la table "plat"
-- -----------------------------------------------
INSERT INTO "plat" ("name", "price", "description", "image", "admin_id") VALUES
('Kebab', 7, 'Pain kebab, viandes (2 max.), sauce et crudités au choix', 'https://assets.afcdn.com/recipe/20210304/118354_w1024h1024c1cx1060cy707.webp', 1),

('Tacos', 8, 'Galette, viandes (2 max.), sauce et crudités au choix', 'https://img.cuisineaz.com/660x660/2019/04/17/i146583-tacos-poulet-curry.jpeg', 1),

('Burger', 8, 'Pain burger, viandes (2 max.), sauce et crudités au choix', 'https://assets.afcdn.com/recipe/20161216/61596_w1024h768c1cx2808cy1872.webp', 1),

('Galette', 7, 'Galette légère, viandes (2 max.), sauce et crudités au choix', 'https://img.cuisineaz.com/660x660/2021/07/11/i179649-tortilla-kebab.jpeg', 1),

('Royal', 10, 'Double pain kebab, viandes (2 max.), sauce et crudités au choix', 'https://assets.afcdn.com/recipe/20210304/118354_w1024h1024c1cx1060cy707.webp', 1),

('Bazooka', 11, 'Double tacos, viandes (2 max.), sauce et crudités au choix', 'https://img.cuisineaz.com/660x660/2019/04/17/i146583-tacos-poulet-curry.jpeg', 1),

('King', 10, 'Maxi burger, viandes (2 max.), sauce et crudités au choix', 'https://assets.afcdn.com/recipe/20161216/61596_w1024h768c1cx2808cy1872.webp', 1),

('Assiette', 11, 'Assiette Garnie, viandes (2 max.), sauce et crudités au choix', 'https://media-cdn.tripadvisor.com/media/photo-s/18/ca/e7/84/notre-assiette-kebab.jpg', 1);


-- -----------------------------------------------
-- Insertion des données dans la table "contact"
-- -----------------------------------------------
INSERT INTO "contact" ("contact") VALUES
('03-85-46-47-70'),
('https://www.facebook.com/stlegerkebab/'),
('12 Place du Capitaine Giraud, 71510 Saint-Léger-sur-Dheune');

SELECT setval('plat_id_seq', (SELECT MAX(id) from "plat"));



COMMIT;
