BEGIN;


-- On s'assure que la table soit supprimée avant d'être créée pour éviter tout problème
DROP TABLE IF EXISTS "plat";



-- ---------------------------------------
-- Table "plat"
-- ---------------------------------------
CREATE TABLE IF NOT EXISTS "plat" (
    "id" integer GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    "name" text NOT NULL,
    "price" integer NOT NULL,
    "created_at" timestamptz NOT NULL DEFAULT CURRENT_TIMESTAMP,
    "updated_at" timestamptz
);

-- -----------------------------------------------
-- Insertion des données dans la table "plat"
-- -----------------------------------------------
INSERT INTO "plat" ("name", "price") VALUES
('Kebab', 7),
('Tacos', 8);



SELECT setval('plat_id_seq', (SELECT MAX(id) from "plat"));



COMMIT;